### ISSUE TITLE
purefb_hardware_health

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#10]
@genegr Hi, is there a documentation on what health alert $values for purefb_hardware_health metric mean?

Current Possible values I see are 0, 1, 2

**Comment by genegr** [comment]
Hi @jmg011, your note made me think this is not the right way to set that
metric. Let me change it so that the status is reported as a label and the
metric is always '1'.

**Comment by jmg011** [comment]
@genegr Thank you. Let me know when this is fixed. The current metric shows value 1 for the flashblades which are de-staged and Not in an active configuration, so that generated some alerts. Which we want to avoid.

**Comment by genegr** [comment]
Fixed in the 1.0.2 version. Will fix also for FB.
