### ISSUE TITLE
Update useragent string to reflect calling platform

### ISSUE THREAD

**Issue by sdodsley** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#102]
The current `useragent` string returns that the OpenMetrics exporter is hitting the backend array, which is reported to Pure for telemetry purposes.
It would be good if we could also/otherwise expose the platform using the OME to get observability data, eg. DataDog, NewRelic, OTel, etc.

**Comment by genegr** [comment]
We could merely take the original caller user-agent and put it into the comments string part of the final user-agent, like this

Pure_FA_OpenMetrics_exporter/1.0 (Prometheus/2.44.0)

This respects the user-agent synthax and can give us the information about the caller. If that sounds, I can easily add the code.

**Comment by sdodsley** [comment]
That would be perfect. Please implement

**Comment by chrroberts-pure** [comment]
closed by #113
