### ISSUE TITLE
Array Load Statistics metric

### ISSUE THREAD

**Issue by imperatives** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#107]
We recently deployed the pure-fa-openmetrics-exporter into our Prometheus/Grafana Mimir cluster.  Thank you for offering this option to your customers!  One of the metrics that we closely track in the Pure1 Manage UI that we would like to consume is load.  Can you please provide information on how the Array Load Statistics are calculated?  If the metrics needed aren't currently exposed by the pure-fa-openmetrics exporter could we please request this be added? 

Thank you!

**Comment by sdodsley** [comment]
Load is a calculated value only provided by the Pure1 platform. It is not something available directly from the FlashArray itself.
I believe the value is derived from numerous data points, including some not visible to public API endpoints.
Also note that the load value in Pure1 is not real-time.
Based on this there is no opportunity to provide this value through the near real-time OpenMetrics interface.

**Comment by imperatives** [comment]
Thanks for the quick response @sdodsley.  If the necessary metrics are exposed through the public api in the future.  It would be appreciated if the promql queries necessary the calculate load could be provided in an example recording rule(s).  Promql does arithmetic quite well so I imagine that shouldn't be the barrier.

**Comment by chrroberts-pure** [comment]
https://support.purestorage.com/Pure1/Pure1_Manage/013_Pure1_Manage_-_REST_API/Pure1_Manage_-_REST_API__Reference

The Pure1 REST API /metrics endpoint provides array_total_load if you wish to programmatically collect load for your arrays.

However, as Simon mentioned- since it is not local to the array, it will not be able to be exported by the this exporter.

**Comment by imperatives** [comment]
Interesting.  Thanks for the additional information @chrroberts-pure!
