### ISSUE TITLE
purefa_alerts_open not reporting correctly

### ISSUE THREAD

**Issue by BadrZef** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#108]
We have pure-fa-openmetrics-exporter on 1.0.12 (think same issue might be on 1.0.13) and some alerts are not reporting the matching fields correctly. For example the last alert with code 5177 is reporting severity value on summary field, sounds like a hop mismatching

You can see below the difference of outputs between a well scrapped alert and the one with wrong matching of values

![image](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/159773918/83f8618d-66df-454c-b121-d92e1b87f895)

Thanks

**Comment by chrroberts-pure** [comment]
Hi! Thank you for the issue. 

I think this MAY be an issue with the JSON that's returned from the Purity API causing a major break in the string. 

It would be very very helpful to get some of the raw output from /alerts from your array so I can test this further. 

Can you please send us an email at pure-observability@purestorage.com to schedule a call to gather this debug information? Thanks!

**Comment by imperatives** [comment]
@chrroberts-pure We are experiencing the same label value mismatching in the `purefa_alerts_open` metric.  Let me know if you need any additional information.

**Comment by chrroberts-pure** [comment]
@imperatives , yes that would be very helpful to grab the Alerts endpoint from your array.

````
// Get API versions available 
curl -k https://gse-array01/api/api_version

// Use latest API version (this example is 2.30) and paste in Array API token
curl -k -D --location --request POST 'https://<array-mgmt-vip>/api/2.30/login' --header 'api-token: <api-token>'

// From the headers of the login, grab the x-auth-token and query Alerts
curl -k -D - --location 'https://<array-mgmt-vip>/api/2.30/alerts' --header 'Accept: application/json' --header 'x-auth-token: <x-auth-token received from headers from the login>'
````

I would recommend NOT to paste the output from your array on here, but please email us the results. Thank you!

**Comment by chrroberts-pure** [comment]
Hi @imperatives @BadrZef - I've just submitted PR #109 to help us resolve this issue. It will be included in the next release.
