### ISSUE TITLE
purefb_open_events_total metric is not found in pure-fb-om-exporter:0.9.0 version

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#11]
purefb_open_events_total metric is not found in pure-fb-om-exporter:0.9.0 version

Is it replaced by purefb_hardware_health metric?

**Comment by genegr** [comment]
It has been replaced by the **purefa_alerts_open** metric in this specific exporter (FlashArray), and by **purefb_alerts_open** for FlashBlade.
