### ISSUE TITLE
No error handling when an FA REST 'API Token' or Array 'endpoint' is incorrect

### ISSUE THREAD

**Issue by chrroberts-pure** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#12]
Currently when an incorrect API Token or endpoint is given to the exporter it will return HTTP 200 and provide the go metrics, but provide no purefa metrics.

We should implement some handling to provide an error when the API Token is incorrect and/or the endpoint is not reachable.

**Comment by genegr** [comment]
Agreed. Will amend the code for that. And thanks for spotting the issue!

**Comment by genegr** [comment]
Fixed in v1.0.2 for this exporter and on v1.0.1 for the FB exporter.
