### ISSUE TITLE
[new metrics proposal] Volume snapshot metrics

### ISSUE THREAD

**Issue by BadrZef** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#128]
Can we have list of volume snapshots and maybe transfer statistics ? The metrics are available on Rest API 

![image](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/159773918/16086b41-2748-4713-a373-f94389f8a3bd)

![image](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/159773918/72d8c5f4-df32-4f0a-9f3e-349d5f55df45)

**Comment by sdodsley** [comment]
@BadrZef whilst these statistics are available, we have to be aware of the amount of time it can take to generate a full list of snapshots on arrays with the transfer data. Imagine a fully populated array with thousands of snapshots (yes, we do see those), the time for the response is prohibitive and would potentially lead to missed data depending on the polling interval of open metrics client.
We do offer other toolsets for getting this information from FlashArrays, specifically, [Pure's FlashArray Ansible Collection](https://galaxy.ansible.com/ui/repo/published/purestorage/flasharray/) when the `purefa_info` module, utilising the `snapshots` subset will provide this information in JSON format.
