### ISSUE TITLE
(question not an issue) Helm chart available?

### ISSUE THREAD

**Issue by amlucent** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#139]
My organization is (attempting) to use the included k8s solution outlined in the repo for monitoring our Pure Arrays via Prometheus/grafana.  We will utilize this on a vmware Tanzu platform on a dark site where many of the networks have no internet or outside connectivity.  

I am merely requesting my internal vmware tanzu admins create the container for me (the storage team) to utilize because my knowledge of Kubernetes is elementary, they are asking me to ask you, is there a helm chart either official or even an example one that can be modified available for this project? 

They are telling me having a premade helm chart will make the deployment and requirements gathering for our air gapped networks much more streamlined.

**Comment by sdodsley** [comment]
@amlucent we do not have a Helm chart, but there is an example k8s simple deployment and operator provided here: https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/tree/master/examples/config/k8s
Please try this and see if it is sufficient for your admins.

**Comment by amlucent** [comment]
@sdodsley the response I was given is not that this is not a show stopper to not have a helm chart and they will look at doing a "ytt" but for supportability into the future "it would be more for future proofing, if they start an official helm chart release schedule they will make appropriate changes as they change purityOS.... otherwise, it is always bespoke, time consuming, and fragile"

Sitting here as the middle man who just wants monitoring, could we call this a feature request?

**Comment by sdodsley** [comment]
@amlucent whilst I understand the request, you should know that the exporter code will shortly be embedded in all upcoming Purity//FA releases (around 6.6.10 I think), therefore the container will not be required for arrays running Purity//FA with the exporter embedded.
This means that there is no concern for any changes to upcoming Purity releases affecting the current container as it will only be required for existing and therefore stable Purity//FA versions.
Based on this, unfortunately, we will not be developing a helm chart as it's life span would be very short.
