### ISSUE TITLE
Warning docker-compose.yaml - **`version` is obsolete**

### ISSUE THREAD

**Issue by raekins** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#144]
WARN[0000] ../pure-fa-openmetrics-exporter/examples/config/docker/docker-compose.yaml: **`version` is obsolete**

Can we remove Version to get rid of the warning message ?

**Comment by chrroberts-pure** [comment]
Yes, looking at the spec - I agree, i've submitted #145 to resolve this. 

We take PRs if you are interested in submitting one in the future. Thank you!
