### ISSUE TITLE
docker-compose.yaml file using deprecated storage.tsdb.retention replace with 'storage.tsdb.retention.time

### ISSUE THREAD

**Issue by raekins** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#146]
warn deprecation_notice="'storage.tsdb.retention' flag is deprecated use 'storage.tsdb.retention.time'

**Comment by sdodsley** [comment]
@raekins what versions of docker and prometheus are you using?
BTW - you could always raise a PR yourself to fix this...
