### ISSUE TITLE
AWS Requirement

### ISSUE THREAD

**Issue by OkieCalUnix** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#162]
Hello Team, 

I have a need to convert my configuration to AWS Linux, and was hoping to get confirmation weather this OS is supported with the The Pure Storage OpenMetrics exporter?
 
Thanks!
 Phillip Bruce

**Comment by sdodsley** [comment]
@OkieCalUnix Are you planning on using the OME binary in AWS Linux or do you want an AWS Linux-based container to use in Amazon ECS?

**Comment by OkieCalUnix** [comment]
We currently running RHEL 7.9 on our VMWare environment, but I am willing to try container one, but our AWS team has recently switched to AWS Linux 2 as the base if we use that one. I'm willing to try an AWS Linux-based container. Just need to ensure I have all the requirements down so we can migrate the RHEL to AWS version.

Thanks for your help

**Comment by OkieCalUnix** [comment]
I want to get a response.  I appreciate SDODSLEY's response but have not seen enough to answer my initial question.

What OS is required to run the exporter on AWS?
RHEL 7.9 above or specific release
Ubunto which release
Centos 7.9 above
ECS - What the requirement to run using this AWS feature?

others?

Thanks for taking time to respond.

**Comment by chrroberts-pure** [comment]
Hi @OkieCalUnix there's no specific OS requirement. It can be built using Go on any architecture using the makefile https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter?tab=readme-ov-file#local-development

The container uses alpine linux, and that can be changed by changing the https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/blob/master/build/docker/Dockerfile file. 

you can use any image in https://hub.docker.com/_/golang

**Comment by OkieCalUnix** [comment]
Christopher,

Thanks, I will give AWS Linux 2 a try. But I don't have the patience to compile code. The dependencies vary in how the code is written specifically for a variant. I tried that before with RHEL 7.9, and nothing but grief.  It takes too many cycles to figure out the dependencies. I used to do that over 20+ years ago cause most unix variants had to be in c code. Now, Kernels has drastically changed, and I just stick to using binaries. Now I have to learn another compiler.  I guess c and gcc compilers are getting harder to link the code together.  Since the binaries is already built for RHEL I'll likely go that route. 

I would like to see binaries in other flavors if possible.  

other suggestions are welcome. I appreciate everyone time and effort in this.

Thanks,

**Comment by chrroberts-pure** [comment]
We have our published binaries that I just tested with Amazon Linux 2 and 2023 on AMD64. 

https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/releases

Under assets, select `linux-amd64.tar.gz`

if you need other platforms than amd64, please let us know.
