### ISSUE TITLE
Mediator status

### ISSUE THREAD

**Issue by ligerard** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#26]
In which metric could i find mediator status ?

**Comment by genegr** [comment]
It makes sense, so I would go for implementing that. I would not use the mediator_status label as it is redundant with the value of the metric, or in case you want to use it then the value should always be 1.

**Comment by ligerard** [comment]
thank you for considering my request.

**Comment by genegr** [comment]
Added in v1.0.5
