### ISSUE TITLE
Pure block exporter does not work

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#3]
**Note:** Re-creating Issue on this Repo: 

I ran the exporter on docker. Disabled SSL check.

As we discussed this in our 1:1 meeting: 

The logs say:

[2022-03-30 00:38:32 +0000] [1] [INFO] packages: sanic-routing==0.7.2
[2022-03-30 00:38:32 +0000] [1] [INFO] Starting worker [1]

When I try to access the end-point /metrics, it does not return anything. It says site cannot be reached. I double checked on the port numbers and everything.

http://fqdn:9491/metrics

curl -G 'http://localhost:9498'
curl: (7) Failed connect to localhost:9498; Connection refused

**Comment by cmautner1** [comment]
Hello, just looking into this a bit.... your curl call is to port 9498.  Is this correct?  9491 should be the port used by default... When I recreated I get a similar error message.  Didn't know if you had some type of port redirection setup for your container.

> 
> cmautner@cmautner--MacBookPro16 ~ % curl -G 'http://localhost:9491'
> curl: (52) Empty reply from server
> cmautner@cmautner--MacBookPro16 ~ % curl -G 'http://localhost:9492'
> curl: (7) Failed to connect to localhost port 9492 after 8 ms: Connection refused

**Comment by jmg011** [comment]
@cmautner1 I had mapped to both the ports for testing. Same error.

**Comment by genegr** [comment]
The new exporter listens by default to "any" ip address of the host on which it runs and on port 9490. Both the ip and port are configurable, also for the Docker image.
