### ISSUE TITLE
Replication monitoring

### ISSUE THREAD

**Issue by ligerard** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#32]
Hi,
Have you plan to include some metrics about "Active Cluster" , distant snapshot (protection group),  safe mode , network activity ...?

**Comment by sdodsley** [comment]
@ligerard we are working on adding replication telemetry in the next few weeks. Hopefully this will give you what you are looking for.

**Comment by genegr** [comment]
Pods performance metrics are already provided. Some were missing, but the vast majority of those is now availabre from release 1.0.4.
