### ISSUE TITLE
docker compose prometheus yml adoption

### ISSUE THREAD

**Issue by sven-kiel** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#34]
Hi Eugenio, please could you change the prometheus.yml file for docker-compose setup, to match the required pattern for "endpoint" specification. In the file is written:

`endpoint: YOUR_FLASHARRAY_IP`

but if you specify those endpoint params without any brackets you will receive a GO unmarshal str error. 

Defining the endpoint params like:

`endpoint: [10.220.113.14]`

would solve the problem.

**Comment by genegr** [comment]
Fixed in v1.0.5
