### ISSUE TITLE
pure-fa-openmetrics-exporter ERROR :Target authorization token is missing and Endpoint parameter is missing

### ISSUE THREAD

**Issue by blalyasar** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#49]
Hello

I want to run project but give me a error after on web site

<img width="936" alt="image" src="https://user-images.githubusercontent.com/49458946/228399914-bcb7968a-7743-405b-8f77-7d8284eadad0.png">

ERROR :Target authorization token is missing
<img width="936" alt="image" src="https://user-images.githubusercontent.com/49458946/228399826-398ea64e-a690-4317-9864-9c09ad9866a0.png">

how to run this:
./out/bin/pure-fa-om-exporter  --tokens ./token.yaml
token.yaml file is

array_id1:
 address: “10.100.100.100”
 api_token: “44basdasdasdadse4c6-3453123123127"

is this valid for AND yaml file  ?
can you help me anyone 

And after I can saw this screen but not runner 

![image](https://user-images.githubusercontent.com/49458946/228399729-a2faaaac-23cf-48b4-a4e3-4f76a2d1ce2f.png)

**Comment by james-laing** [comment]
The browser is unable to pass the endpoint or authorisation token. The exporter does not need to be configured in any way.
Try testing with cURL 
`curl -H 'Authorization: Bearer 44basdasdasdadse4c6-3453123123127' -X GET 'http://<exporter_ip>:9490/metrics/array?endpoint=10.100.100.100'
`

There are a few troubleshooting tips here:
https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/tree/master/extra/grafana

**Comment by blalyasar** [comment]
> The browser is unable to pass the endpoint or authorisation token. The exporter does not need to be configured in any way. Try testing with cURL `curl -H 'Authorization: Bearer 44basdasdasdadse4c6-3453123123127' -X GET 'http://<exporter_ip>:9490/metrics/array?endpoint=10.100.100.100' `
> 
> There are a few troubleshooting tips here: https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/tree/master/extra/grafana



I did test. But ı dont see the on the browser
This output:

# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 8
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.19.4"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 583088
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 583088
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4288
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 360
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.714992e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 583088
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 1.630208e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.236416e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 2419
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 1.630208e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 3.866624e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 0
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 2779
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 12000
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 39456
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 48816
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 856064
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 327680
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 327680
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 8.834064e+06
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 5

**Comment by blalyasar** [comment]
> Hi @blalyasar,
> 
> Try with `?endpoint=10.100.100.100`

I am tried
0.0.0.0:9490/metrics/volumes?endpoint=10.100.100.100
 but this same error
Target authorization token is missing

**Comment by sballa-mm** [comment]
> I am tried 0.0.0.0:9490/metrics/volumes?endpoint=10.100.100.100 but this same error Target authorization token is missing

ensure proper indentation in token.yaml

this all works fine for me

**Comment by james-laing** [comment]
@blalyasar it is difficult to see how your token.yaml file is formatted without applying formatting using markdown in your output but I agree with @sballa-mm it could be that your yaml file is not formatted correctly.
Use a yaml validator and ensure you use the quotations correctly `"` or `'` in stead of `“`.

Try this as your `token.yaml`:

```
array_id1:
  address: '10.100.100.100'
  api_token: '44basdasdasdadse4c6-3453123123127'
```

Alternatively if you wish to take an easier route to getting the OME up and running use the docker image directly from quay.io as described here: https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter#docker
```
$ docker run -d -p 9490:9490 --name pure-fa-om-exporter quay.io/purestorage/pure-fa-om-exporter:latest
$ curl -H 'Authorization: Bearer 44basdasdasdadse4c6-3453123123127' -X GET 'http://127.0.0.1:9490/metrics/array?endpoint=10.100.100.100'
```

**Comment by james-laing** [comment]
@blalyasar did you get it working?

**Comment by 6r1zzlyB** [comment]
@blalyasar were you able to resolve the problem?

I am having the same issue. I confirmed that the curl command works fine, but referencing the token.yaml file does not provide any output other then "Target authorization token is missing"

token.yaml
```
array_id1:
  address: 172.31.146.70
  api_token: 434503da-......
array_id2:
  address: 172.31.146.80
  api_token: b8605f85-......
```

**Comment by blalyasar** [comment]
Thanks for everyone .. İt works . But I dont knew what is problem  :) ?
