### ISSUE TITLE
Wrong documentation about endpoint and targets (Prometheus)

### ISSUE THREAD

**Issue by xefil** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#54]
Hello,
Only to share that I've seen the doc here:

https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter#prometheus-configuration

Is not the same as the example here:

https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/blob/master/examples/config/k8s/simple-deployment/prometheus-configmap-multi.yaml

There is the `__param_target` which should be `__param_endpoint`

Bye, Simon

**Comment by genegr** [comment]
Hi,
Thanks for spotting that, I amended the example in the README file with the correct parameter, which is the one of the  https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/blob/master/examples/config/k8s/simple-deployment/prometheus-configmap-multi.yaml config file.
