### ISSUE TITLE
Target authorization token is missing

### ISSUE THREAD

**Issue by 6r1zzlyB** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#59]
I setup the exporter with the local setup process.

I confirmed that the curl command give the following output. 

curl -H 'Authorization: Bearer 4b84cabd-***' -X GET 'http://10.10.10.10:9490/metrics/array?endpoint=bel2-pure1'

```
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 17
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.18.1"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.97776e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 3.97776e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4303
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 702
....
```

But referencing the token.yaml with the following command the page only shows "Target authorization token is missing"

/opt/pure-fa-om-exporter/out/bin/pure-fa-om-exporter -t /opt/pure-fa-om-exporter/token.yaml

Here is my token.yaml
```
array_id1:
  address: 'bel2-pure1'
  api_token: '4b84cabd-***'
array_id2:
  address: '172.31.146.80'
  api_token: 'b8605f85-***'
```

**Comment by james-laing** [comment]
From the output of the curl results below I can't determine if any `purefa_` metrics were returned.

### cURL
The curl command used contains the authorization bearer token and grep for `purefa_info` as this metric is included in all endpoints.
```
curl -H 'Authorization: Bearer 4b84cabd-***' -X GET 'http://10.10.10.10:9490/metrics/array?endpoint=bel2-pure1'  -silent | grep ^purefa_info
```

Now try the query again without the authorisation token to ensure the `token.yaml` is being utilised correctly.
```
curl -X GET 'http://10.10.10.10:9490/metrics/array?endpoint=bel2-pure1' -silent | grep ^purefa_info
```
If that works then you should be good to try in the browser.
If it does not then check the yaml is valid (it certainly looks like it is in your example) and the file is specified on launch.

### Browser
Be sure to specify the device endpoint as the links in the browser won't know which device you wish to connect.

When you enter the URL into the browser with http://10.10.10.10:9490/ and get results like this:
<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pure Storage FlashArray OpenMetrics Exporter</h1>

Type | Endpoint | GET parameters | Description
-- | -- | -- | --
Full metrics | /metrics | endpoint | All array metrics. Expect slow response time.
Array metrics | /metrics/array | endpoint | Provides only array related metrics.
Volumes metrics | /metrics/volumes | endpoint | Provides only volumes related metrics.
Hosts metrics | /metrics/hosts | endpoint | Provides only hosts related metrics.
Pods metrics | /metrics/pods | endpoint | Provides only pods related metrics.
Directories metrics | /metrics/directories | endpoint | Provides only directories related metrics.

The browser defaults to
http://10.10.10.10:9490/metrics/array?endpoint=host

Ensure the device endpoint it specified like so:
http://10.10.10.10:9490/metrics/array?endpoint=bel2-pure1

**Comment by 6r1zzlyB** [comment]
Sorry, on the close button, kid got click happy.

**Comment by pilot7777** [comment]
i am facing the exact same issue. when run with the -t option, get "Target authorization token is missing" error.

**Comment by pilot7777** [comment]
Found the problem. It was missing parameter endpoint. Prometheus scape k8s exporter pod. After adding 
params:
        endpoint: [entry-in-token.yaml]
It works!

**Comment by pilot7777** [comment]
i thought the exporter would just scrape all arrays in API token(s) map file. wish it was true.

**Comment by justinterprated** [comment]
sorry the fix was in the prometheus.yaml?

**Comment by pilot7777** [comment]
yes. we run prometheus in k8s. here is my scrape config
`    - job_name: 'psa1_lab_ams'
      params:
        endpoint: [psa1_lab_ams]
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - prd3028
      relabel_configs:
      - target_label: env
        replacement: AMS
      - source_labels: [__meta_kubernetes_pod_name]
        action: keep
        regex: pure-exporter.*
      - source_labels: [job]
        regex: (.*)
        replacement: $1
        target_label: instance
`

it's kind of cumbersome. have to add these for each array.

**Comment by pilot7777** [comment]
figured out how to multiple target. example in README helps.
```- job_name: pure-fa-probe
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_endpoint
      - source_labels: [__param_endpoint]
        target_label: instance
      - source_labels: [instance]
        regex: (.*)_(.*)_(.*)
        replacement: $3
        target_label: env
      - source_labels: [env]
        action: uppercase
        target_label: env
      - target_label: __address__
        replacement: pure-exporter-probe.prd3028.svc.cluster.local:80
      static_configs:
      - targets:
        - psa1_lab_ams
        - psa2_lab_ams

**Comment by 6r1zzlyB** [comment]
I'm not using k8s.

My config looks to be trying to scrap the output of the exporter.

```
  - job_name: "pure-fa-probe"
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics/pods
    scheme: http
    follow_redirects: true
    #enable_http2: true
    relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: job
        replacement: pure-fa-probe
        action: replace
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_endpoint
        replacement: $1
        action: replace
      - source_labels: [__param_endpoint]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: localhost:9490
        action: replace
    static_configs:
      - targets:
          - 172.31.146.70
          - 172.31.146.80
```

Since the exporter is not able to scrap the arrays with the token, it's pointless to edit the prometheus.yaml file.

**Comment by 6r1zzlyB** [comment]
Fixed my issues.

Needed to call out the array id in the token file with a unique name and use the same refence in the Prometheus config.

token.yaml
```
bel2-pure1:
  address: 172.31.146.70
  api_token: 4b84cabd-********
bel2-pure2:
  address: 172.31.146.80
  api_token: b8605f85-********
```

prometheus.yaml
```
  - job_name: "pure-fa-probe"
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics/pods
    scheme: http
    follow_redirects: true
    #enable_http2: true
    relabel_configs:
      - source_labels: [job]
        separator: ;
        regex: (.*)
        target_label: __tmp_prometheus_job_name
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: job
        replacement: pure-fa-probe
        action: replace
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_endpoint
        replacement: $1
        action: replace
      - source_labels: [__param_endpoint]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: localhost:9490
        action: replace
    static_configs:
      - targets:
          - bel2-pure1
          - bel2-pure2
```
