### ISSUE TITLE
Plugin restarting and collections stopped in Purity 6.4.4 and later

### ISSUE THREAD

**Issue by slackuser1979** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#69]
Hello everyone,

I am use this pure-fa-openmetrics-exporter for Flasharray and Flashblade in the bigest customer in LATAM of Pure Storage.
After upgrade the Purity for version 6.4.5 on two Flasharrays//C, the collects stopping
Bellow, cli show command "docker ps":

[root@~]# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
6d5d03b63270 grafana/grafana "/run.sh" 2 months ago Up 7 days 0.0.0.0:443->3000/tcp pure-fa-openmetrics-exporter-docker-grafana-1
3b549b787bcb quay.io/purestorage/pure-fb-om-exporter:latest "/pure-fb-om-exporte…" 3 months ago Up 7 days 0.0.0.0:9491->9491/tcp pure-fa-openmetrics-exporter-docker-pure-fb-om-exporter-1
fa57c4d7b452 quay.io/purestorage/pure-fa-om-exporter:latest "/usr/local/bin/pure…" 3 months ago Up 31 minutes 0.0.0.0:9490->9490/tcp pure-fa-openmetrics-exporter-docker-pure-fa-om-exporter-1
44db9ab12a38 prom/prometheus "/bin/prometheus --s…" 3 months ago Up 7 days 0.0.0.0:9090->9090/tcp pure-fa-openmetrics-exporter-docker-prometheus-1

I would like help with re-establishing collections on devices running Purity 6.4.4 and later.
NOTE: These devices use file services.
In equipment with version 6.4.3, there was no interruption in collection

**Comment by chrroberts-pure** [comment]
Hi, 

You should be able to pull the latest image by running this command. The latest image was published 7 days ago.

`docker pull quay.io/purestorage/pure-fa-om-exporter:latest` 

You can view this image with `docker image ls` - to make sure it was downloaded. 

You will then need to stop your running container and start a new one using the latest image.

[I found this StackOverflow link to be helpful](https://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed) with some information on how to do this in Docker.

**Comment by chrroberts-pure** [comment]
Also to get the version you are running - you can look at the docker container logs with the `docker logs` command

chrroberts@ ~ % docker logs bd3efb9b9282
2023/07/12 13:40:07 Start Pure FlashArray exporter v1.0.7 on 0.0.0.0:9490

**Comment by genegr** [comment]
@slackuser1979 if you want to deepener troubleshooting the issue you could spin up a sencond instance of the exporter container with the additional --debug flag and then simply query one of the targets that are not working via curl, like this:

% docker run  -p 9495:9495  --rm --name pure-fa-om-exporter quay.io/purestorage/pure-fa-om-exporter -d -p 9495

Notice the missing -d flag for the docker run, that keeps the container running in foreground.
From another terminal window you can then use curl

% curl  -H "Authorization: Bearer b5cb29e7-a81c-b40a-b02a-da2b90c9365e" http://10.225.113.63:9495/metrics/array\?endpoint=10.225.112.90

and you shuld see the full HTTP conversation that happens between the exporter and the target FA in the other window.
