### ISSUE TITLE
Сonnection path state

### ISSUE THREAD

**Issue by maxkushnir** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#83]
I would really appreciate it if you could kindly assist us in finding a solution for monitoring the connection path state of hosts. Specifically, I'm looking to gather information regarding the host connectivity state, which may display path states such as Redundant, Unused Port, Unknown, etc. Health>Connections>Host Connections into one metric.
 
Is it possible to obtain these states in specific metric?

![ca1-flasharray-a06_host_path](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/25609084/c62e788f-4195-40cf-a318-7784489deec2)

**Comment by sdodsley** [comment]
@maxkushnir I believe this information is already exposed as `port_connectivity` from `/metrics/hosts`. This should provide the path status of `Redundant, Uneven, None` etc.

**Comment by sdodsley** [comment]
@maxkushnir I misinformed you. That data is not exposed. I misread the code.
Let me discuss with the team if this is possible to add.

**Comment by chrroberts-pure** [comment]
Tagging new PR that addresses this #84 . Review, and comment if you'd like @maxkushnir @blalyasar
