### ISSUE TITLE
 The OpenMetrics exporter is incorrectly calling the /hardware endpoint

### ISSUE THREAD

**Issue by emaiello** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#89]
Hello,

It sounds like the OpenMetrics exporter is reporting the wrong status while we perform a GET request against the /hardware endpoint and instead a proper drive status while using the **/drives** endpoint.

In the example I'm sharing below we see that using the /drives API endpoint, the Status reported is correct because the drive is failed:

![pure3-tr3_drive_api_status](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/150457310/886ce12b-5795-4ce2-be7a-5266b60475de)

Using the **/hardware** API endpoint, instead, the Status reported is wrong and is shown as "ok" as shown below:
![pure3-tr3_hardware_api_status](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/150457310/a97ac584-c301-47d4-ac0f-c0141357af18)

Pure Array GUI is reporting the correct status:
![array_gui](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/150457310/764ee401-91db-4f69-b04e-fb2f91177a27)

The Pure API version in use for this test is **1.9**
Swagger reference: Pure1 Public REST APIs: https://static.pure1.purestorage.com/api-swagger/index.html

Could you please have a look on this?
Thanks!

**Comment by sdodsley** [comment]
This issue is actually that the `/hardware` endpoint is returning the incorrect information. This should be fixed, rather then fixing the exporter. 
The endpoint error is a bigger issue affecting more than just the exporter.

**Comment by sdodsley** [comment]
Based in the engineering JIRA comments, the `/hardware` endpoint only reports the health of the bay, not the actual drive, so this looks like a valid feature request to add the `/drives` endpoint

**Comment by chrroberts-pure** [comment]
Interesting find! I’ll have to think about how we implement this since they have the same “name” key which is what lead to this confusion. Thanks for the issue.
