### ISSUE TITLE
Enhancements to purefa_alerts_open, collect additional fields.

### ISSUE THREAD

**Issue by lehatdst** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#94]
We would like to see if a request for additional data can be collected to the Alerts_Open endpoint.  We would like to use the data to send alerts to Prometheus's Alert manager, but would like to have the additional data to manage the alerts, to silence the alerts and to have additional documentation when an alert is sent to a pager or MS-Teams channel.   I reviewed the API of the data available and would like to have at least the data that is shown in the GUI (green), plus the "ID" field so that the alert can be managed.

This is what I found available in the REST-API:
The “green” highlighted fields are what is in the GUI, the Promethes fields are the yellow one and the “Severity” field.
![Alert_API](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter/assets/124386328/bfb2d0a8-f314-41d8-be91-d771bcb8a876)

**Comment by chrroberts-pure** [comment]
Hi @lehatdst ! 

Thank you for opening this issue, and I agree that we could add a lot of metadata into some of our alerts. 

Is this something that you would be interested in submitting a PR for? If not, we can assign someone to take a deeper look into this feature request. Thanks!

**Comment by lehatdst** [comment]
I would welcome someone well versed in the PR/coding process.  I would be available to discuss any questions that might arise.

**Comment by lehatdst** [comment]
This was close by mistake.

**Comment by chrroberts-pure** [comment]
Let’s keep this open as issues track our backlog. We will assign someone from our team to manage this issue.

**Comment by sdodsley** [comment]
@lehatdst this fix has been included in the v1.0.12 release.
