### ISSUE TITLE
Inquiry regarding the “Purestorage” version supported by the current “exporter” and the previous “exporter”

### ISSUE THREAD

**Issue by 3DPIT** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#96]
Inquiry regarding the “Purestorage” version supported by the current “exporter” and the previous “exporter”

Previously, data from “purestorage” was imported to the site below.
https://github.com/PureStorage-OpenConnect/pure-exporter

And currently, I proceeded with the “exporter” of the site.

There was a phenomenon in which data could not be retrieved in "purestorage" version 4.7.10.
 
So what I'm curious about is whether the previous "exporter" and the current "exporter" support "purestorage" of 4.7.10, respectively.

I would like to know whether a "purestorage" version of each is provided in its entirety, or to what extent it is covered.

**Comment by sdodsley** [comment]
The current OpenMetrics exporter do not require the `purestorage` SDK, nor any other Python package. The application has been converted to GoLang and has all pre-requisites inbuilt.

**Comment by 3DPIT** [comment]
> The current OpenMetrics exporter do not require the `purestorage` SDK, nor any other Python package. The application has been converted to GoLang and has all pre-requisites inbuilt.

which versions of pure-storage does this repository support for monitoring?

pure-storage 4.x version is supported by pure-fa-openmetrics-exporter?

**Comment by james-laing** [comment]
The Pure Storage OpenMetrics Exporter requires a minimum of REST API version 2.4 which was introduced in Purity version 6.1.0.

**Comment by 3DPIT** [comment]
> Pure Storage OpenMetrics 내보내기에는 Purity 버전 6.1.0에 도입된 최소 REST API 버전 2.4가 필요합니다.

I want to export data from Purity version 4.10.17, is there a way?

**Comment by sdodsley** [comment]
I don't beleive there was ever a Purity//FA 4.10.17 release. The highest 4.10 release was 4.10.13 and that is EOL.
You should reach out to your local Pure Storage team and arrange for this array to be upgraded.
The OpenMetrics exporter requires a minimum of 6.1.0

**Comment by 3DPIT** [comment]
Iam sorry 

> I don't beleive there was ever a Purity//FA 4.10.17 release. The highest 4.10 release was 4.10.13 and that is EOL. You should reach out to your local Pure Storage team and arrange for this array to be upgraded. The OpenMetrics exporter requires a minimum of 6.1.0

sorry. You were talking about version 4.7.10, not version 4.10.17.

There is currently a purestorage mib file on the official site.
Are you planning to upgrade your mib file?

**Comment by sdodsley** [comment]
4.7.10 is very EOL and should be upgraded as soon as possible.
The MIB that is shipped with Purity (accessible from the GUI -Settings -> System -> SNMP window - select three dots for menu with Download MIB) is the only MIB available.
MIBs are not under the control of this team, but I don't believe that there are any planned updates to the MIB.
You would need to upgrade to a supported version of Purity to see if the supplied MIB is any different.

**Comment by 3DPIT** [comment]
Thank you. It helped me a lot.
